### ISSUE TITLE
list of decoders?

### ISSUE THREAD

**Issue by bitwombat** [ymtszw/elm-xml-decode#12]
Hi, thanks for this library!

I have data like this:

```
<root>
    <station name="Moranbah (Utah Dr)">
        <measurement name="Particle PM10" rating_name="Very Good" rating="1" index="30">15</measurement>
        <measurement name="Particle PM2.5" rating_name="Very Good" rating="1" index="19.6">4.9</measurement>
    </station>
</root>
```

I want output like this:

```
Ok [ 
       {rating_name = "Very Good", measurement = 15}
     , {rating_name = "Very Good", measurement = 19.6}
]
```
I can make a `Decoder` that parses one line of that, but get a "Multiple Nodes" error as soon as there are more than one `<measurement>`.

I've been racking my brain with `list`, but then I get two different lists:
```
Ok (["Very Good", "Very Good"], [15, 19.6])
```

Should I just zip that together?

I was also thinking maybe I need to use `node`?

Would appreciate some guidance!

Thanks.

**Comment by ymtszw** [comment]
@bitwombat Hi 👋 
Would you please paste your current decoder so I can start from there?

**Comment by bitwombat** [comment]
```
type alias Measurement =
    { rating_name : String
    , measurement : Float
    }


oneLineDecoder : Decoder Measurement
oneLineDecoder =
    map2 Measurement
        (path [ "measurement" ] (single <| stringAttr "rating_name"))
        (path [ "measurement" ] (single float))


measurementDecoder : Decoder (List Measurement)
measurementDecoder =
    path [ "category", "region", "station" ] (list oneLineDecoder)
```

Or if you want to see the test:
https://github.com/bitwombat/air-quality

**Comment by ymtszw** [comment]
> but get a "Multiple Nodes" error as soon as there are more than one `<measurement>`.

Let's start off of here. "Multiple Nodes" error happens on `single`, where it expects there is exactly one node matching the criteria.

In your `oneLineDecoder` it says:

```elm
    path [ "measurement" ] (single <| stringAttr "rating_name")
```

this expects "there is only one `<measurement>` node with `rating_name` attribute in my scope". And the scope here under the effect of `measurementDecoder`, is `<station> ... </station>`. Therefore it breaks!

Also worth noting, as stated in [`path` doc](https://package.elm-lang.org/packages/ymtszw/elm-xml-decode/latest/Xml-Decode#path), `path` collects all matching nodes in breadth-first manner, and brings them into the scope.

With these in mind, you should first "collect" exactly what you want. Try this:

```elm
    path [ "category", "region", "station", "measurement" ]
```

It "collects" two (and more) of your `<measurement>` nodes.

Then you can apply `oneLineDecoder` to each node using `list`, like so:

```elm
measurementDecoder =
    path [ "category", "region", "station", "measurement" ] (list oneLineDecoder)

oneLineDecoder =
    map2 Measurement (stringAttr "rating_name") float
```

Yes, locater function `path` is not always needed, if you are already "on" the targeting node(s)! I know this is somewhat confusing but let the types guide you 🤞 

A similar answer is now written in the library test, FYI https://github.com/ymtszw/elm-xml-decode/blob/master/tests/IssueCases.elm#L29-L39

Tell me if it doesn't work!

**Comment by ymtszw** [comment]
As an alternative, you might want to split the scope on `<station>` node, in that case you can:

```elm
measurementDecoder =
    path [ "category", "region", "station" ] (single stationDecoder)

stationDecoder =
    path [ "measurement" ] (list oneLineDecoder)

oneLineDecoder =
    map2 Measurement (stringAttr "rating_name") float
```

(I believe it works but not confident enough 😛 )

Anyway the point is you must give proper "quantization" on the scope specified by `path`, due to how XML documents are structured.

Let's say if you have many `<station>`s in a `<region>`, you give `list stationDecoder` to `path [ "category", "region", "station" ]`! It results in `Decoder (List (List Measurement))`, which groups measurements by regions!

**Comment by bitwombat** [comment]
There are so many key points in your reply that I had missed. Thanks Yu!
