### ISSUE TITLE
Path to Attribute

### ISSUE THREAD

**Issue by atlewee** [ymtszw/elm-xml-decode#2]
This package seems nice, just started playing with it.. BUt I have a problem decoding attributes...
How do I decode attributes of a nested Node?
```
path [ "node1", "node2"]  (??????)
```
(node2 has no children, only attributes)
I know I have to use this decoder:
```
stringAttr "node2Attribute"
```
But how do I feed node2 to it ?

**Comment by ymtszw** [comment]
Hi, thanks for trying the package!

Decoding an attribute of a node should be like this:

```elm
run (path [ "tag", "nested" ] (single (stringAttr "value"))) "<root><tag><nested value='attr1'></nested></tag></root>"
--> Ok "attr1"
```

(added as an example in master 1309866)

Basically, you need to supply elementary decoders (in your case `stringAttr "node2Attribute"`)
to `ListDecoder` generator (like `single`), defining its quantization.

**Comment by atlewee** [comment]
That was a quick reply. 👍 
And it works. Thanks!
