### ISSUE TITLE
Support for Elm 0.19

### ISSUE THREAD

**Issue by mibuthu** [ymtszw/elm-xml-decode#3]
Hello, may I ask if and when we can expect an update for Elm 0.19?

**Comment by ymtszw** [comment]
Was waiting for upstream packages/tools updates but they seem ready.
I'll get my hands on this on this weekend.
Thanks for ping 🎃

**Comment by mibuthu** [comment]
Thanks, that's great news.

**Comment by ymtszw** [comment]
...aaand it's done :) https://package.elm-lang.org/packages/ymtszw/elm-xml-decode/2.0.0/

There are several breaking changes introduced on this occasion. Please check out [CHANGELOG.md](https://github.com/ymtszw/elm-xml-decode/blob/master/CHANGELOG.md).

Always feel free to report any issues found!
