### ISSUE TITLE
Attribute of List element

### ISSUE THREAD

**Issue by mibuthu** [ymtszw/elm-xml-decode#4]
Hi, I have a problem with getting the attributes of the list item when I use a nested Decoder:

With this example XML:
```elm
exampleXml =
    "<root>  
        <ListItem id=\"1\"><value>a</value></ListItem>  
        <ListItem id=\"2\"><value>b</value></ListItem>  
    </root>"
```

it is no problem to get the attributes:
```elm
exampleDecoder1 =
    path [ "ListItem" ] (list (intAttr "id"))

run exampleDecoder1 exampleXml
```

but if I want to create a "Sub-Decoder" to decode multiple sub-items of the list item I cannot access the attribute of the list item element itself:
```elm
exampleDecoder2 =
    path [ "ListItem" ] (list listItemDecoder)

listItemDecoder =
    map2 Tuple.pair
        (path [] (single (intAttr "id")))
        (path [ "value" ] (single string))

run exampleDecoder2 exampleXml
```
Here I get the error:
`"Attribute 'id' not found. At: /ListItem, Node: <value>a</value>`

Am I doing something wrong?
How can I achieve this?

**Comment by ymtszw** [comment]
Try this:
```elm
listItemDecoderFixed =
    map2 Tuple.pair
        (intAttr "id")
        (path [ "value" ] (single string))
```

The point is, those sub-decoders take `<ListItem id=\"1\"><value>a</value></ListItem>`,
so you do not need to "dig into" its contents, just apply attribute decoders directly.

**Comment by mibuthu** [comment]
Thanks for the quick help, it works perfectly.
Now as I can see it, the solution is logical, but before I didn't hit on that.
