### ISSUE TITLE
Missing oneOf Function

### ISSUE THREAD

**Issue by cjduncana** [ymtszw/elm-xml-decode#5]
Hello there 👋 

Thanks for creating this package. Very useful package to parse XML and it works like a charm.

I'm in need of function similar to [JSON Decode's `oneOf`](https://package.elm-lang.org/packages/elm-lang/core/latest/Json-Decode#oneOf). I want to model to shapes of XML. The normal response and the errors response. They have different shapes that I can capture in a custom type. In JSON, I would use `oneOf` to resolve different shapes into the same type.

Can your library provide this function? If you need any more information or assistance, don't hesitate in letting me know.

I hope you enjoy your day!
Chris Duncan

**Comment by ymtszw** [comment]
Very reasonable and frankly, I overlooked its necessity. Thanks for pointing out! 👍 

It should be not super hard to include so I will go for it.

**Comment by cjduncana** [comment]
Awesome! Thanks for helping me out. If you need anything, I'm here.

**Comment by ymtszw** [comment]
It's done, but due to required `Error` structure change, it resulted in major version up. Published as [3.0.0](https://package.elm-lang.org/packages/ymtszw/elm-xml-decode/3.0.0/).

See [CHANGELOG.md](https://github.com/ymtszw/elm-xml-decode/blob/3.0.0/CHANGELOG.md) for details.
